{ ... }:

{
  imports = [
    ../core/session.nix
    ../core/shell.nix
    ../core/xdg.nix
    ../cli/fish.nix
    ../cli/git.nix
    ../cli/github.nix
    ../cli/prompt.nix
    ../cli/ssh.nix
    ../cli/terminal.nix
    ../cli/alacritty.nix
    ../cli/ghostty.nix
    ../cli/htop.nix
    ../cli/lazygit.nix
    ../cli/tmux.nix
    ../cli/glow.nix
    ../cli/yazi.nix
    ../development/editor.nix
    ../development/emacs.nix
    ../development/zed.nix
    ../development/tools.nix
    ../development/codex.nix
    ../development/pi.nix
    ../desktop/apps.nix
    ../desktop/fonts.nix
    ../desktop/fcitx5.nix
    ../desktop/lockscreen.nix
    ../desktop/mime.nix
    ../desktop/mpv.nix
    ../desktop/niri.nix
    ../desktop/sway.nix
    ../services/rclone.nix
    ../secrets/sops.nix
    ../secrets/local-files.nix
    ../communication/mail.nix
  ];
}
